language: ruby
sudo: false
rvm:
- 2.6.3
services:
- docker
before_install:
- docker pull mumuki/mumuki-elixir-worker
deploy:
  provider: rubygems
  api_key:
    secure: LjhfsRpbgJEG9t3ryoIYrnWPonEk1cVL9EYebVHg35KPQ72MoLRDkkZQcyu2gxfLCbu0/EslkKxUQxO6v7KJ/XdYL8USf0W3BJwgakINxGyWFU8h2eYGH/hpLOnrrUgoN7J+P/lfFSmZVDKy8J1Ko5du6m+9ZPc2/qH3drclb8YHVjNIGeAGKMeI7URZ9CqH6/WXGiyw97jvdbG2pV0ReRrVFI/DRqInGAe35jo+CezFFCgs9/TgykimYmcVrSMIonlMw8H1cBniDnxERLT4X+pWhZc6vlDFVuRl+pAiNCCwPTFD4bYGB6MYA/Oif+2KjAVdfrWeXhk9evJSG4RscFJOrGNc1i+VHhTfM5M2qyEckFU37FrxQeAz3Nr6jxgDfSIJ/LZhtCkUg07q09YVQxLS+cu0LMsm0EcHu0Cvq+pn7NuyGHP3bStTFKbMTZOIqWWoyfyIeS5pOUmx/AVkGp8j6Tsxni/tkbbqFx+WZnHd8vdzbWBqJF2QtEtDPgVbX5Zwv6bflPvIe8L7JAHppcgKurMwP7ulUGFoslFa38GuBbDIqGDYi2u6YE+twZXFKTkISUMnP/xKazCuSh8U2CZJeztvdj2K296cuTCB3gNZFKPPgjWIU/9ICkZ7rBgoKrOh0e66ohpDT3c0ECWupzgQGDBLVkX4xmVZ6TFlT10=
  gem: mumuki-elixir-runner
  on:
    tags: true
    repo: mumuki/mumuki-elixir-runner
